<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampingZonesSeeder extends Seeder
{
    public function run(): void
    {
        $zones = [
            // ── North Tunisia ─────────────────────────────────────────────────
            [
                'nom'              => 'Cap Serrat',
                'city'             => 'Sejnane',
                'region'           => 'Bizerte',
                'commune'          => 'Sejnane',
                'description'      => 'Remote pine forest camping with direct access to pristine Mediterranean coastline.',
                'full_description' => 'Cap Serrat is one of Tunisia\'s most pristine natural camping zones. Located along the northern coast near Bizerte, this area features dense cork oak and pine forests that meet secluded pebble beaches. The zone offers various camping spots ranging from beachfront sites to forest clearings, with minimal infrastructure to preserve its wild character. The area is rich in birdlife and offers excellent snorkeling in crystal-clear waters.',
                'terrain'          => 'Forest & Coastal',
                'difficulty'       => 'easy',
                'lat'              => 37.2167,
                'lng'              => 9.2333,
                'adresse'          => 'Cap Serrat, Sejnane, Bizerte',
                'distance'         => '90 km from Tunis',
                'altitude'         => '20m',
                'access_type'      => 'road',
                'accessibility'    => 'Vehicle accessible via paved road',
                'rating'           => 4.8,
                'reviews_count'    => 124,
                'best_season'      => json_encode(['Spring', 'Summer', 'Autumn']),
                'activities'       => json_encode(['Hiking', 'Swimming', 'Snorkeling', 'Bird Watching', 'Photography', 'Fishing']),
                'facilities'       => json_encode(['Fire pits', 'Basic shelters', 'Natural water source nearby', 'Parking area', 'Trash disposal']),
                'rules'            => json_encode([
                    'Respect nature — leave no trace',
                    'Fires only in designated fire pits',
                    'No loud music after 10 PM',
                    'Pack out all trash',
                    'Respect wildlife — observe from a distance',
                ]),
                'contact_phone'    => '+216 72 000 000',
                'contact_email'    => null,
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> true,
                'is_closed'        => false,
                'danger_level'     => 'low',
                'max_capacity'     => 50,
                'map_zoom_level'   => 14,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
            [
                'nom'              => 'Ain Draham Forest Camp',
                'city'             => 'Ain Draham',
                'region'           => 'Jendouba',
                'commune'          => 'Ain Draham',
                'description'      => 'High-altitude cork oak forest with cool temperatures and misty mornings — unique in Tunisia.',
                'full_description' => 'Ain Draham sits at over 800 metres elevation in the Khroumirie Mountains, making it one of the few places in Tunisia where snow falls in winter. The surrounding forests of cork oak, Aleppo pine and wild boar trails make for exceptional hiking. The Beni M\'tir lake nearby offers fishing and boat trips. Spring brings carpets of wildflowers and mild temperatures ideal for extended camping stays.',
                'terrain'          => 'Mountain Forest',
                'difficulty'       => 'medium',
                'lat'              => 36.7833,
                'lng'              => 8.6833,
                'adresse'          => 'Route Forestière, Ain Draham, Jendouba',
                'distance'         => '170 km from Tunis',
                'altitude'         => '850m',
                'access_type'      => 'road',
                'accessibility'    => 'Vehicle accessible, 4x4 recommended for forest tracks',
                'rating'           => 4.6,
                'reviews_count'    => 89,
                'best_season'      => json_encode(['Spring', 'Summer', 'Autumn']),
                'activities'       => json_encode(['Hiking', 'Mountain Biking', 'Bird Watching', 'Wildlife Viewing', 'Photography', 'Fishing']),
                'facilities'       => json_encode(['Toilets', 'Barbecue areas', 'Parking', 'Picnic tables', 'Water points']),
                'rules'            => json_encode([
                    'No hunting — protected wildlife area',
                    'Fires in designated areas only',
                    'Keep dogs on a leash',
                    'Do not pick plants or disturb wildlife',
                ]),
                'contact_phone'    => '+216 78 655 000',
                'contact_email'    => 'forets.aindraham@environment.tn',
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> true,
                'is_closed'        => false,
                'danger_level'     => 'low',
                'max_capacity'     => 80,
                'map_zoom_level'   => 13,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
            [
                'nom'              => 'Lac de Bizerte Waterfront',
                'city'             => 'Bizerte',
                'region'           => 'Bizerte',
                'commune'          => 'Bizerte',
                'description'      => 'Calm lakeside camping beside the largest lake in North Africa with stunning sunset views.',
                'full_description' => 'The shores of Lac de Bizerte offer one of Tunisia\'s most accessible camping experiences. The lake, connected to the Mediterranean by a canal, creates a unique microclimate with excellent fishing and birdwatching. Flamingos and herons are frequent visitors. The historic city of Bizerte with its Andalusian old quarter is just minutes away.',
                'terrain'          => 'Lakeside',
                'difficulty'       => 'easy',
                'lat'              => 37.2744,
                'lng'              => 9.8734,
                'adresse'          => 'Route du Lac, Bizerte',
                'distance'         => '65 km from Tunis',
                'altitude'         => '5m',
                'access_type'      => 'road',
                'accessibility'    => 'Fully accessible by paved road',
                'rating'           => 4.3,
                'reviews_count'    => 67,
                'best_season'      => json_encode(['Spring', 'Summer', 'Autumn']),
                'activities'       => json_encode(['Fishing', 'Kayaking', 'Bird Watching', 'Swimming', 'Photography', 'Bonfire']),
                'facilities'       => json_encode(['Toilets', 'Showers', 'Parking', 'Picnic tables', 'Boat launch']),
                'rules'            => json_encode([
                    'No motorized boats after 8 PM',
                    'Fishing permit required',
                    'Keep the shoreline clean',
                ]),
                'contact_phone'    => '+216 72 431 000',
                'contact_email'    => null,
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> false,
                'is_closed'        => false,
                'danger_level'     => 'low',
                'max_capacity'     => 100,
                'map_zoom_level'   => 13,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],

            // ── Central Tunisia ───────────────────────────────────────────────
            [
                'nom'              => 'Jebel Zaghouan Summit Camp',
                'city'             => 'Zaghouan',
                'region'           => 'Zaghouan',
                'commune'          => 'Zaghouan',
                'description'      => 'Rocky mountain camping at the foot of Tunisia\'s most iconic peak with ancient Roman ruins nearby.',
                'full_description' => 'Jebel Zaghouan rises dramatically to 1295 metres and is visible from Tunis on clear days. The national park surrounding it protects Barbary macaques, golden eagles and rare orchids. The Temple des Eaux, a Roman water temple at the mountain\'s base, supplied ancient Carthage with water via a 132km aqueduct. Camping here combines adventure hiking with extraordinary archaeological history.',
                'terrain'          => 'Rocky Mountain',
                'difficulty'       => 'hard',
                'lat'              => 36.3833,
                'lng'              => 10.1500,
                'adresse'          => 'Parc National de Zaghouan, Zaghouan',
                'distance'         => '60 km from Tunis',
                'altitude'         => '900m',
                'access_type'      => 'trail',
                'accessibility'    => '4x4 to base camp, hiking trail to summit',
                'rating'           => 4.7,
                'reviews_count'    => 103,
                'best_season'      => json_encode(['Spring', 'Autumn']),
                'activities'       => json_encode(['Rock Climbing', 'Hiking', 'Bird Watching', 'Photography', 'Stargazing', 'Wildlife Viewing']),
                'facilities'       => json_encode(['Basic toilets at base camp', 'Parking', 'Ranger station']),
                'rules'            => json_encode([
                    'Stay on marked trails',
                    'No collecting of plants, rocks or animals',
                    'Camping permit required from national park office',
                    'No fires above 600m altitude',
                ]),
                'contact_phone'    => '+216 72 678 000',
                'contact_email'    => 'zaghouan.park@environment.tn',
                'contact_website'  => 'https://www.environnement.tn',
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> true,
                'is_closed'        => false,
                'danger_level'     => 'moderate',
                'max_capacity'     => 30,
                'map_zoom_level'   => 13,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
            [
                'nom'              => 'Jebel Chambi National Park',
                'city'             => 'Kasserine',
                'region'           => 'Kasserine',
                'commune'          => 'Kasserine',
                'description'      => 'Camping at Tunisia\'s highest peak — 1544m — with Atlas cedar forests and rare wildlife.',
                'full_description' => 'Jebel Chambi is Tunisia\'s highest mountain at 1544 metres and a UNESCO Biosphere Reserve. The national park protects the last Atlas cedar forests in Tunisia, as well as Barbary leopards (extremely rare), golden eagles and wild boar. The landscape shifts dramatically with altitude from scrubland to dense cedar forest. Winter camping here can involve snow and requires proper gear.',
                'terrain'          => 'High Mountain & Cedar Forest',
                'difficulty'       => 'hard',
                'lat'              => 35.2167,
                'lng'              => 8.6833,
                'adresse'          => 'Parc National de Jebel Chambi, Kasserine',
                'distance'         => '280 km from Tunis',
                'altitude'         => '1200m',
                'access_type'      => 'trail',
                'accessibility'    => '4x4 required, trail access only above 1000m',
                'rating'           => 4.9,
                'reviews_count'    => 56,
                'best_season'      => json_encode(['Spring', 'Summer', 'Autumn']),
                'activities'       => json_encode(['Hiking', 'Rock Climbing', 'Bird Watching', 'Wildlife Viewing', 'Photography', 'Stargazing']),
                'facilities'       => json_encode(['Ranger station', 'Emergency shelter', 'Parking at trailhead']),
                'rules'            => json_encode([
                    'Permit required — obtain from Kasserine DGFE office',
                    'No fires in the cedar zone',
                    'Do not approach or feed wildlife',
                    'Pack all waste out',
                    'Register your itinerary with rangers before ascending',
                ]),
                'contact_phone'    => '+216 77 470 000',
                'contact_email'    => 'chambi.park@environment.tn',
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> true,
                'is_closed'        => false,
                'danger_level'     => 'moderate',
                'max_capacity'     => 20,
                'map_zoom_level'   => 12,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],

            // ── South Tunisia ─────────────────────────────────────────────────
            [
                'nom'              => 'Chott el-Djerid Desert Camp',
                'city'             => 'Tozeur',
                'region'           => 'Tozeur',
                'commune'          => 'Tozeur',
                'description'      => 'Camp on the edge of the world\'s largest salt flat — surreal sunsets and Saharan stargazing.',
                'full_description' => 'Chott el-Djerid is a vast endorheic salt lake covering over 7000 km². In summer it dries completely to a blinding white salt flat; in winter shallow water creates extraordinary mirages. Camping on its shores offers some of the most otherworldly landscapes in the world, and the absence of light pollution makes it one of Tunisia\'s premier stargazing locations. The Star Wars filming locations at Ong Jmal are nearby.',
                'terrain'          => 'Desert & Salt Flat',
                'difficulty'       => 'medium',
                'lat'              => 33.7167,
                'lng'              => 8.4333,
                'adresse'          => 'Route de Kebili, Tozeur',
                'distance'         => '450 km from Tunis',
                'altitude'         => '17m',
                'access_type'      => 'road',
                'accessibility'    => 'Accessible by paved road, 4x4 for off-road routes',
                'rating'           => 4.9,
                'reviews_count'    => 201,
                'best_season'      => json_encode(['Autumn', 'Winter', 'Spring']),
                'activities'       => json_encode(['Stargazing', 'Photography', 'Camel Riding', 'Desert Safari', 'Nature Photography', 'Sunset Watching']),
                'facilities'       => json_encode(['Basic camp fire areas', 'No permanent facilities — carry all supplies']),
                'rules'            => json_encode([
                    'Always carry sufficient water — minimum 4L per person per day',
                    'Inform someone of your route before camping',
                    'No driving on the salt flat in wet season',
                    'Leave no trace — salt flat is a fragile ecosystem',
                ]),
                'contact_phone'    => '+216 76 452 000',
                'contact_email'    => null,
                'contact_website'  => 'https://www.tourisme.gov.tn',
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> false,
                'is_closed'        => false,
                'danger_level'     => 'moderate',
                'max_capacity'     => 40,
                'map_zoom_level'   => 11,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
            [
                'nom'              => 'Ksar Ghilane Desert Oasis',
                'city'             => 'Ksar Ghilane',
                'region'           => 'Tataouine',
                'commune'          => 'Ghomrassen',
                'description'      => 'Remote hot spring oasis deep in the Sahara — camping among dunes with natural thermal pool.',
                'full_description' => 'Ksar Ghilane is one of Tunisia\'s most extraordinary camping destinations — a natural hot spring oasis at the edge of the Grand Erg Oriental. The thermal pool maintains a constant 30°C and is surrounded by towering sand dunes. A Roman fort (Tisavar) guards the oasis, adding historical depth to the desert experience. 4x4 convoys from Douz or Matmata bring adventurers here for multi-day desert treks.',
                'terrain'          => 'Desert Dunes & Oasis',
                'difficulty'       => 'medium',
                'lat'              => 32.9833,
                'lng'              => 9.6333,
                'adresse'          => 'Ksar Ghilane, Tataouine',
                'distance'         => '570 km from Tunis',
                'altitude'         => '100m',
                'access_type'      => 'mixed',
                'accessibility'    => '4x4 required — paved road to Douz then desert piste',
                'rating'           => 4.95,
                'reviews_count'    => 312,
                'best_season'      => json_encode(['Autumn', 'Winter', 'Spring']),
                'activities'       => json_encode(['Camel Riding', 'Desert Safari', 'Stargazing', 'Swimming', 'Photography', 'Quad Biking', 'Sand Boarding']),
                'facilities'       => json_encode(['Hot spring pool', 'Basic camp facilities', 'Camel guides available', 'Emergency radio']),
                'rules'            => json_encode([
                    '4x4 and experienced guide mandatory',
                    'Never venture into dunes alone',
                    'Carry GPS and satellite phone for emergencies',
                    'Respect the oasis ecosystem — no soap in the spring',
                    'Minimum 3L water per person beyond spring supply',
                ]),
                'contact_phone'    => '+216 75 631 000',
                'contact_email'    => null,
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> false,
                'is_closed'        => false,
                'danger_level'     => 'moderate',
                'max_capacity'     => 60,
                'map_zoom_level'   => 12,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
            [
                'nom'              => 'Matmata Troglodyte Camp',
                'city'             => 'Matmata',
                'region'           => 'Gabès',
                'commune'          => 'Matmata',
                'description'      => 'Unique underground Berber village camping — the original Star Wars Tatooine filming location.',
                'full_description' => 'Matmata\'s landscape of craters and troglodyte dwellings is unlike anywhere else on Earth. The Berber inhabitants carved homes into the soft rock thousands of years ago — a natural response to the extreme desert heat. George Lucas used the area as Luke Skywalker\'s home planet Tatooine. Camping near the village allows immersion in Berber culture, ancient architecture, and the surreal moonscape terrain of southern Tunisia.',
                'terrain'          => 'Desert Craters & Rock',
                'difficulty'       => 'easy',
                'lat'              => 33.5433,
                'lng'              => 9.9683,
                'adresse'          => 'Matmata, Gabès',
                'distance'         => '430 km from Tunis',
                'altitude'         => '400m',
                'access_type'      => 'road',
                'accessibility'    => 'Accessible by paved road from Gabès',
                'rating'           => 4.5,
                'reviews_count'    => 178,
                'best_season'      => json_encode(['Autumn', 'Winter', 'Spring']),
                'activities'       => json_encode(['Photography', 'Cultural Tour', 'Hiking', 'Stargazing', 'Camel Riding', 'Desert Safari']),
                'facilities'       => json_encode(['Local guesthouses nearby', 'Parking', 'Guided tours available']),
                'rules'            => json_encode([
                    'Respect local Berber customs and privacy',
                    'Ask permission before photographing residents',
                    'No alcohol in public areas',
                ]),
                'contact_phone'    => '+216 75 240 000',
                'contact_email'    => null,
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> false,
                'is_closed'        => false,
                'danger_level'     => 'low',
                'max_capacity'     => 80,
                'map_zoom_level'   => 13,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],

            // ── East Coast ────────────────────────────────────────────────────
            [
                'nom'              => 'Cap Bon Peninsula Camp',
                'city'             => 'Kelibia',
                'region'           => 'Nabeul',
                'commune'          => 'Kelibia',
                'description'      => 'White sandy beaches and Carthaginian ruins on Tunisia\'s most beautiful peninsula.',
                'full_description' => 'The Cap Bon peninsula juts into the Mediterranean between the Gulf of Tunis and Gulf of Hammamet, creating a microclimate perfect for camping almost year-round. Kelibia\'s Byzantine fort overlooks one of Tunisia\'s finest beaches. The peninsula is famous for its Muscat wine, citrus groves, and excellent diving along its rocky northern shore. The ancient Phoenician settlement of Kerkouane — a UNESCO World Heritage Site — is nearby.',
                'terrain'          => 'Coastal & Agricultural',
                'difficulty'       => 'easy',
                'lat'              => 36.8467,
                'lng'              => 11.1167,
                'adresse'          => 'Route de la Plage, Kelibia, Nabeul',
                'distance'         => '100 km from Tunis',
                'altitude'         => '10m',
                'access_type'      => 'road',
                'accessibility'    => 'Fully accessible by paved road',
                'rating'           => 4.6,
                'reviews_count'    => 145,
                'best_season'      => json_encode(['Spring', 'Summer', 'Autumn']),
                'activities'       => json_encode(['Swimming', 'Snorkeling', 'Diving', 'Fishing', 'Hiking', 'Photography', 'Kayaking']),
                'facilities'       => json_encode(['Toilets', 'Showers', 'Parking', 'Beach access', 'Nearby restaurants']),
                'rules'            => json_encode([
                    'No camping on designated swimming beaches',
                    'Respect marine protected zones',
                    'No spearfishing without permit',
                ]),
                'contact_phone'    => '+216 72 296 000',
                'contact_email'    => null,
                'contact_website'  => null,
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> false,
                'is_closed'        => false,
                'danger_level'     => 'low',
                'max_capacity'     => 120,
                'map_zoom_level'   => 13,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
            [
                'nom'              => 'Ile de Kuriat Marine Reserve',
                'city'             => 'Monastir',
                'region'           => 'Monastir',
                'commune'          => 'Sayada',
                'description'      => 'Island camping on a protected marine reserve — nesting site for Mediterranean loggerhead turtles.',
                'full_description' => 'The Kuriat islands, 15km off the coast of Monastir, are one of the Mediterranean\'s most important nesting sites for the endangered loggerhead sea turtle (Caretta caretta). The islands are a protected marine reserve with crystal-clear waters and a thriving reef. Camping is permitted with advance authorization from the APAL (Coastal Protection Agency). Snorkeling with sea turtles is a once-in-a-lifetime experience.',
                'terrain'          => 'Island & Marine',
                'difficulty'       => 'medium',
                'lat'              => 35.7833,
                'lng'              => 11.0333,
                'adresse'          => 'Ile de Kuriat, Monastir (boat access from Sayada)',
                'distance'         => '160 km from Tunis',
                'altitude'         => '5m',
                'access_type'      => 'boat',
                'accessibility'    => 'Boat access only — 30 min from Sayada port',
                'rating'           => 4.8,
                'reviews_count'    => 43,
                'best_season'      => json_encode(['Summer']),
                'activities'       => json_encode(['Snorkeling', 'Diving', 'Bird Watching', 'Wildlife Viewing', 'Photography', 'Swimming']),
                'facilities'       => json_encode(['No permanent facilities — carry all supplies', 'Emergency radio at ranger post']),
                'rules'            => json_encode([
                    'Permit required from APAL Monastir office',
                    'Do not disturb turtle nesting sites — marked with stakes',
                    'No fires during nesting season (May–October)',
                    'Carry all waste back to mainland',
                    'Maximum stay: 3 nights',
                ]),
                'contact_phone'    => '+216 73 460 000',
                'contact_email'    => 'kuriat.reserve@apal.nat.tn',
                'contact_website'  => 'https://www.apal.nat.tn',
                'is_public'        => true,
                'status'           => true,
                'is_protected_area'=> true,
                'is_closed'        => false,
                'danger_level'     => 'low',
                'max_capacity'     => 15,
                'map_zoom_level'   => 14,
                'source'           => 'admin',
                'centre_id'        => null,
                'added_by'         => null,
            ],
        ];

        foreach ($zones as &$zone) {
            $zone['created_at'] = now();
            $zone['updated_at'] = now();
        }

        DB::table('camping_zones')->insert($zones);

        $this->command->info('✅ ' . count($zones) . ' camping zones seeded successfully.');
    }
}