<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

/**
 * Seeds additional camping zones, private centres, and public centres in Tunisia.
 * Uses insertOrIgnore to safely run alongside CampingZonesSeeder & CampingCentresSeeder.
 */
class TunisiaCampingSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // ─────────────────────────────────────────────────────────────────────
        // 1. ZONES DE CAMPING
        // ─────────────────────────────────────────────────────────────────────
        $zones = [

            // ── Nord ─────────────────────────────────────────────────────────

            [
                'nom'               => 'Parc National de l\'Ichkeul',
                'city'              => 'Mateur',
                'region'            => 'Bizerte',
                'commune'           => 'Mateur',
                'description'       => 'Zone humide classée UNESCO — flamants roses, hérons et bivouac au bord du lac.',
                'full_description'  => 'Le parc national de l\'Ichkeul est l\'un des derniers grands lacs d\'eau douce d\'Afrique du Nord classé patrimoine mondial de l\'UNESCO. Chaque hiver, des centaines de milliers d\'oiseaux migrateurs — flamants roses, canards siffleurs, oies cendrées — colonisent ses rives. Le Jebel Ichkeul (511 m) offre un panorama exceptionnel sur le lac et la mer. Le camping sauvage sur la rive nord reste l\'une des expériences ornithologiques les plus rares du pays.',
                'terrain'           => 'Zone humide & colline',
                'difficulty'        => 'easy',
                'lat'               => 37.1667,
                'lng'               => 9.6667,
                'adresse'           => 'Parc National Ichkeul, Mateur, Bizerte',
                'distance'          => '80 km de Tunis',
                'altitude'          => '15m',
                'access_type'       => 'road',
                'accessibility'     => 'Accessible en voiture via la route de Mateur',
                'rating'            => 4.7,
                'reviews_count'     => 88,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Observation des oiseaux', 'Randonnée', 'Photographie', 'Pêche', 'Bivouac']),
                'facilities'        => json_encode(['Poste de garde-faune', 'Parking', 'Sentiers balisés', 'Tables de pique-nique']),
                'rules'             => json_encode([
                    'Permis requis auprès de l\'ANPE',
                    'Interdiction de déranger les oiseaux nicheurs',
                    'Feux interdits dans la zone humide',
                    'Chiens interdits',
                ]),
                'contact_phone'     => '+216 72 465 000',
                'contact_email'     => 'ichkeul@anpe.nat.tn',
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => true,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 40,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Tabarka — Côte des Aiguilles',
                'city'              => 'Tabarka',
                'region'            => 'Jendouba',
                'commune'           => 'Tabarka',
                'description'       => 'Camping entre falaises de grès et mer turquoise — meilleur spot de plongée du nord-ouest.',
                'full_description'  => 'La côte des Aiguilles à Tabarka est un alignement spectaculaire de rochers granitiques émergeant de la mer, offrant l\'un des paysages les plus saisissants du littoral tunisien. Le fond marin exceptionnel en fait un paradis pour la plongée sous-marine (corail rouge, mérous, langoustes). Les forêts de pins et de chênes-lièges descendent jusqu\'à la mer, créant des emplacements de bivouac ombragés à quelques mètres des flots.',
                'terrain'           => 'Côtier & forestier',
                'difficulty'        => 'easy',
                'lat'               => 36.9547,
                'lng'               => 8.7574,
                'adresse'           => 'Côte des Aiguilles, Tabarka, Jendouba',
                'distance'          => '180 km de Tunis',
                'altitude'          => '10m',
                'access_type'       => 'road',
                'accessibility'     => 'Route goudronnée jusqu\'à Tabarka, piste pour les falaises',
                'rating'            => 4.8,
                'reviews_count'     => 156,
                'best_season'       => json_encode(['Printemps', 'Été', 'Automne']),
                'activities'        => json_encode(['Plongée sous-marine', 'Snorkeling', 'Randonnée', 'Escalade', 'Pêche', 'Photographie']),
                'facilities'        => json_encode(['Douches', 'WC', 'Parking', 'Club de plongée à proximité', 'Restaurants']),
                'rules'             => json_encode([
                    'Pas de camping sur les rochers — risque de chute',
                    'Chasse sous-marine interdite dans la zone protégée',
                    'Feux uniquement dans les emplacements désignés',
                ]),
                'contact_phone'     => '+216 78 673 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 80,
                'map_zoom_level'    => 14,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Lac de Beni M\'tir',
                'city'              => 'Ain Draham',
                'region'            => 'Jendouba',
                'commune'           => 'Ain Draham',
                'description'       => 'Lac de barrage en altitude dans les forêts de chênes-lièges — pêche et nuits fraîches garanties.',
                'full_description'  => 'Niché à 800 mètres d\'altitude dans les montagnes de la Kroumirie, le lac de Beni M\'tir est entouré d\'une forêt de chênes-lièges et de pins où vivent sangliers, genettes et reptiles rares. L\'eau limpide du lac attire les pêcheurs de truites et d\'anguilles. Les matinées brumeuses et les nuits fraîches — parfois sous les 10°C même en été — en font l\'un des seuls endroits en Tunisie où le camping est agréable en juillet et août.',
                'terrain'           => 'Lac de montagne & forêt',
                'difficulty'        => 'easy',
                'lat'               => 36.7600,
                'lng'               => 8.7000,
                'adresse'           => 'Barrage Beni M\'tir, Ain Draham, Jendouba',
                'distance'          => '170 km de Tunis',
                'altitude'          => '800m',
                'access_type'       => 'road',
                'accessibility'     => 'Route goudronnée depuis Ain Draham',
                'rating'            => 4.6,
                'reviews_count'     => 72,
                'best_season'       => json_encode(['Printemps', 'Été', 'Automne']),
                'activities'        => json_encode(['Pêche', 'Kayak', 'Randonnée', 'Observation des oiseaux', 'Photographie', 'Bivouac']),
                'facilities'        => json_encode(['Embarcadère', 'Parking', 'Auberge de jeunesse à 3 km', 'Barbecue']),
                'rules'             => json_encode([
                    'Permis de pêche obligatoire',
                    'Feux interdits à moins de 30m du lac',
                    'Pas de baignade — lac de retenue d\'eau potable',
                ]),
                'contact_phone'     => '+216 78 655 500',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 60,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'El Haouaria — Cap Bon Nord',
                'city'              => 'El Haouaria',
                'region'            => 'Nabeul',
                'commune'           => 'El Haouaria',
                'description'       => 'Falaises spectaculaires à la pointe de Cap Bon — paradis des faucons et point de passage des migrateurs.',
                'full_description'  => 'El Haouaria est située à l\'extrémité nord du Cap Bon, là où le détroit de Sicile est le plus étroit. Chaque printemps, des milliers de rapaces migrateurs — buses, faucons d\'Éléonore, éperviers — s\'y arrêtent lors de leur traversée vers l\'Europe. Les grottes phéniciennes taillées dans le grès fournissaient autrefois les pierres de Carthage. Le camping sur les hauteurs offre une vue plongeante sur la Méditerranée et, par temps clair, sur le cap Bon sicilien.',
                'terrain'           => 'Falaises côtières',
                'difficulty'        => 'easy',
                'lat'               => 37.0548,
                'lng'               => 11.0098,
                'adresse'           => 'El Haouaria, Nabeul',
                'distance'          => '100 km de Tunis',
                'altitude'          => '60m',
                'access_type'       => 'road',
                'accessibility'     => 'Route goudronnée, piste pour les falaises',
                'rating'            => 4.5,
                'reviews_count'     => 94,
                'best_season'       => json_encode(['Printemps', 'Automne']),
                'activities'        => json_encode(['Observation des rapaces', 'Randonnée', 'Plongée', 'Photographie', 'Spéléologie', 'Pêche']),
                'facilities'        => json_encode(['Parking', 'Restaurants du village', 'WC publics']),
                'rules'             => json_encode([
                    'Ne pas déranger les faucons nicheurs (mars–août)',
                    'Camping sur les falaises interdit — zone instable',
                    'Grottes : visite guidée recommandée',
                ]),
                'contact_phone'     => '+216 72 269 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => true,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 50,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Korbous — Sources Thermales',
                'city'              => 'Korbous',
                'region'            => 'Nabeul',
                'commune'           => 'Korbous',
                'description'       => 'Camping sur falaises dominant le golfe de Tunis — sources d\'eau chaude naturelles en bord de mer.',
                'full_description'  => 'Korbous est un village thermal niché entre falaises rocheuses et Méditerranée, à la pointe ouest du Cap Bon. Les sources jaillissent directement de la roche à 60°C et se mêlent à l\'eau de mer dans des vasques naturelles creusées dans la falaise — une expérience unique en Tunisie. Le chemin côtier pittoresque offre des vues saisissantes sur le golfe de Tunis. Le camping sur les hauteurs permet une arrivée matinale aux vasques avant les touristes de la journée.',
                'terrain'           => 'Côtier & falaises',
                'difficulty'        => 'easy',
                'lat'               => 36.8139,
                'lng'               => 10.5658,
                'adresse'           => 'Korbous, Nabeul',
                'distance'          => '60 km de Tunis',
                'altitude'          => '80m',
                'access_type'       => 'road',
                'accessibility'     => 'Route goudronnée pittoresque depuis Soliman',
                'rating'            => 4.4,
                'reviews_count'     => 113,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Bains thermaux', 'Randonnée côtière', 'Pêche', 'Photographie', 'Snorkeling']),
                'facilities'        => json_encode(['Sources thermales publiques', 'WC', 'Parking', 'Cafés', 'Hébergements locaux']),
                'rules'             => json_encode([
                    'Respecter les horaires d\'accès aux vasques (6h–20h)',
                    'Feux interdits sur les falaises',
                    'Ne pas jeter de déchets dans la mer',
                ]),
                'contact_phone'     => '+216 72 289 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 60,
                'map_zoom_level'    => 14,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],

            // ── Centre ────────────────────────────────────────────────────────

            [
                'nom'               => 'Jebel Boukornine',
                'city'              => 'Hammam-Lif',
                'region'            => 'Ben Arous',
                'commune'           => 'Hammam-Lif',
                'description'       => 'Parc national aux portes de Tunis — bivouac sur les crêtes avec vue panoramique sur le golfe.',
                'full_description'  => 'Le Jebel Boukornine (576 m) est le seul parc national de Tunisie situé à moins de 20 km du centre de la capitale. Ses deux sommets jumeaux, visibles de tout le golfe de Tunis, offrent un panorama à 360° sur la métropole, la mer et les chaînes atlasiques. La forêt de chênes kermès et de pistachiers lentisques abrite des lézards ocellés, des renards de Rüppell et des espèces botaniques endémiques. Idéal pour un bivouac de week-end depuis Tunis.',
                'terrain'           => 'Montagne & maquis',
                'difficulty'        => 'medium',
                'lat'               => 36.7100,
                'lng'               => 10.5400,
                'adresse'           => 'Parc National Boukornine, Hammam-Lif, Ben Arous',
                'distance'          => '18 km de Tunis',
                'altitude'          => '400m',
                'access_type'       => 'trail',
                'accessibility'     => 'Sentier depuis Hammam-Lif (40 min à pied)',
                'rating'            => 4.3,
                'reviews_count'     => 201,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Randonnée', 'Escalade', 'Observation des oiseaux', 'Photographie', 'Bivouac', 'Course nature']),
                'facilities'        => json_encode(['Poste de rangers', 'Parking au bas du parc', 'Sentiers balisés']),
                'rules'             => json_encode([
                    'Permis de bivouac requis (ANPE Ben Arous)',
                    'Feux strictement interdits — forêt sensible',
                    'Accès au sommet fermé après 18h',
                    'Emportez tous vos déchets',
                ]),
                'contact_phone'     => '+216 71 430 000',
                'contact_email'     => 'boukornine@anpe.nat.tn',
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => true,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 25,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Jebel Serj — Forêt de Siliana',
                'city'              => 'Maktar',
                'region'            => 'Siliana',
                'commune'           => 'Maktar',
                'description'       => 'Plateau boisé à 1357 m — forêts de pins et ruines romaines de Mactaris à portée de randonnée.',
                'full_description'  => 'Le Jebel Serj culmine à 1357 mètres et constitue l\'un des massifs forestiers les moins fréquentés de Tunisie. Ses forêts de pins d\'Alep, de cèdres de l\'Atlas et de cyprès abritent des rapaces nicheurs. Le site archéologique de Mactaris (Maktar), cité berbère puis romaine, est à seulement 5 km. En hiver, la neige recouvre régulièrement les sommets. L\'été, les températures nocturnes descendent à 10°C — rare privilège en Tunisie centrale.',
                'terrain'           => 'Montagne & forêt de pins',
                'difficulty'        => 'medium',
                'lat'               => 35.8700,
                'lng'               => 9.2000,
                'adresse'           => 'Jebel Serj, Maktar, Siliana',
                'distance'          => '140 km de Tunis',
                'altitude'          => '1100m',
                'access_type'       => 'road',
                'accessibility'     => '4x4 recommandé sur les pistes forestières',
                'rating'            => 4.4,
                'reviews_count'     => 47,
                'best_season'       => json_encode(['Printemps', 'Été', 'Automne']),
                'activities'        => json_encode(['Randonnée', 'VTT', 'Observation des oiseaux', 'Archéologie', 'Bivouac', 'Photographie']),
                'facilities'        => json_encode(['Parking à Maktar', 'Gîte rural à 8 km', 'Pistes forestières balisées']),
                'rules'             => json_encode([
                    'Feux uniquement dans les emplacements forestiers désignés',
                    'Ne pas couper de bois vert',
                    'Signaler votre itinéraire aux forestiers locaux',
                ]),
                'contact_phone'     => '+216 78 870 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 40,
                'map_zoom_level'    => 12,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Gorges de Selja — Oued Derb',
                'city'              => 'Metlaoui',
                'region'            => 'Gafsa',
                'commune'           => 'Metlaoui',
                'description'       => 'Canyon sauvage traversé par le Lézard Rouge — bivouac entre falaises de calcaire ocre.',
                'full_description'  => 'Les gorges de Selja, taillées par l\'Oued Seldja dans le calcaire ocre, sont l\'un des paysages les plus dramatiques de Tunisie. Le célèbre train « Lézard Rouge » — un ancien wagon bey restauré — traverse ces gorges depuis Metlaoui. Mais les randonneurs qui descendent le canyon à pied découvrent une dimension autrement plus sauvage : cascades, grottes, source d\'eau fraîche et parois de 200 mètres. Bivouaquer dans le fond du canyon, sous un ciel constellé, est une expérience inoubliable.',
                'terrain'           => 'Canyon & falaises calcaires',
                'difficulty'        => 'medium',
                'lat'               => 34.3300,
                'lng'               => 8.3900,
                'adresse'           => 'Gorges de Selja, Metlaoui, Gafsa',
                'distance'          => '380 km de Tunis',
                'altitude'          => '350m',
                'access_type'       => 'trail',
                'accessibility'     => 'Descente à pied depuis Metlaoui (2h)',
                'rating'            => 4.7,
                'reviews_count'     => 63,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Randonnée canyon', 'Escalade', 'Photographie', 'Stargazing', 'Bivouac']),
                'facilities'        => json_encode(['Source d\'eau dans le canyon', 'Gare de Metlaoui à l\'entrée', 'Aucune installation permanente']),
                'rules'             => json_encode([
                    'Ne jamais descendre après une pluie — risque de crue soudaine',
                    'Prévoir 4L d\'eau par personne',
                    'Emportez une lampe frontale — gorges très sombres',
                    'Laisser zéro déchet',
                ]),
                'contact_phone'     => '+216 76 240 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'moderate',
                'max_capacity'      => 30,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],

            // ── Sud ──────────────────────────────────────────────────────────

            [
                'nom'               => 'Erg Oriental — Douz',
                'city'              => 'Douz',
                'region'            => 'Kébili',
                'commune'           => 'Douz',
                'description'       => 'Mer de dunes de sable doré aux portes du Grand Sahara — bivouac bédouin authentique.',
                'full_description'  => 'Douz, surnommée « la porte du désert », est le point de départ naturel pour les bivouacs dans l\'Erg Oriental tunisien. Les dunes de sable fin doré s\'étendent à perte de vue au-delà de la ville. Selon la saison, les températures diurnes varient de 15°C (janvier) à 45°C (juillet). Le Festival International du Sahara de Douz (novembre) célèbre la culture bédouine : fantasia, courses de chameaux et musique berbère. Les nuits sahariennes, dégagées et silencieuses, offrent une voûte étoilée d\'une richesse rare.',
                'terrain'           => 'Erg sableux',
                'difficulty'        => 'medium',
                'lat'               => 33.4549,
                'lng'               => 9.0247,
                'adresse'           => 'Erg Oriental, Douz, Kébili',
                'distance'          => '420 km de Tunis',
                'altitude'          => '100m',
                'access_type'       => 'mixed',
                'accessibility'     => 'Route goudronnée jusqu\'à Douz, dromadaire ou 4x4 pour les erg',
                'rating'            => 4.8,
                'reviews_count'     => 287,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Bivouac saharien', 'Balade à dromadaire', 'Quad', 'Sandboard', 'Stargazing', 'Photographie', 'Safari 4x4']),
                'facilities'        => json_encode(['Guides locaux', 'Locations de dromadaires', 'Camping équipé à l\'entrée', 'Restaurants bédouins']),
                'rules'             => json_encode([
                    'Toujours partir accompagné d\'un guide local',
                    'Minimum 4L d\'eau par personne par jour',
                    'Communiquer votre itinéraire avant de partir',
                    'Pas de feu en période estivale (risque d\'incendie)',
                ]),
                'contact_phone'     => '+216 75 470 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'moderate',
                'max_capacity'      => 120,
                'map_zoom_level'    => 12,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Oasis de Nefta — Corbeille',
                'city'              => 'Nefta',
                'region'            => 'Tozeur',
                'commune'           => 'Nefta',
                'description'       => 'Bivouac au cœur d\'une oasis de 10 000 palmiers encerclée par le désert — havre de fraîcheur saharienne.',
                'full_description'  => 'Nefta est considérée comme la perle spirituelle du désert tunisien. Sa « Corbeille » — une dépression naturelle accueillant plus de 10 000 palmiers-dattiers et des centaines de sources jaillissantes — est l\'une des plus belles oasis d\'Afrique du Nord. Ville mystique, Nefta est le berceau du soufisme en Tunisie. Bivouaquer dans les jardins de la Corbeille, au son de l\'eau et sous les étoiles, avec l\'adhan du matin comme réveil, est une expérience transformatrice.',
                'terrain'           => 'Oasis & désert',
                'difficulty'        => 'easy',
                'lat'               => 33.8703,
                'lng'               => 7.8776,
                'adresse'           => 'La Corbeille, Nefta, Tozeur',
                'distance'          => '490 km de Tunis',
                'altitude'          => '60m',
                'access_type'       => 'road',
                'accessibility'     => 'Accessible par route goudronnée depuis Tozeur',
                'rating'            => 4.9,
                'reviews_count'     => 176,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Randonnée dans l\'oasis', 'Photographie', 'Bivouac', 'Visite culturelle', 'Dégustation de dattes', 'Stargazing']),
                'facilities'        => json_encode(['Hébergements locaux', 'Restaurants traditionnels', 'Guides', 'Parking']),
                'rules'             => json_encode([
                    'Respecter les propriétés privées dans l\'oasis',
                    'Pas de feu parmi les palmiers',
                    'Tenue décente requise dans la ville',
                ]),
                'contact_phone'     => '+216 76 430 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 80,
                'map_zoom_level'    => 14,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Ghomrassen — Ksour du Sud',
                'city'              => 'Ghomrassen',
                'region'            => 'Tataouine',
                'commune'           => 'Ghomrassen',
                'description'       => 'Bivouac parmi les greniers berbères (ksour) perchés — architecture saharienne millénaire au crépuscule.',
                'full_description'  => 'La région de Tataouine abrite les ksour (singulier : ksar) les plus spectaculaires d\'Afrique du Nord — des greniers collectifs berbères perchés sur des pitons rocheux, aux portes de la hamada. Ksar Ouled Soltane, Ksar Hadada et Ksar Ghilane voisin offrent chacun une atmosphère unique. Bivouaquer à proximité de ces structures millénaires, sous un ciel saharien d\'une clarté absolue, avec les silhouettes orangées des ksour au coucher du soleil, constitue l\'une des expériences les plus singulières du pays.',
                'terrain'           => 'Hamada & pitons rocheux',
                'difficulty'        => 'easy',
                'lat'               => 33.0500,
                'lng'               => 10.1600,
                'adresse'           => 'Ghomrassen, Tataouine',
                'distance'          => '530 km de Tunis',
                'altitude'          => '350m',
                'access_type'       => 'road',
                'accessibility'     => 'Route goudronnée depuis Tataouine',
                'rating'            => 4.7,
                'reviews_count'     => 132,
                'best_season'       => json_encode(['Automne', 'Hiver', 'Printemps']),
                'activities'        => json_encode(['Visite des ksour', 'Randonnée', 'Photographie', 'Bivouac', 'Stargazing', 'Safari culturel']),
                'facilities'        => json_encode(['Maisons d\'hôtes locales', 'Restaurants berbères', 'Guides certifiés', 'Parking']),
                'rules'             => json_encode([
                    'Ne pas escalader les ksour sans guide',
                    'Respecter les sites classés patrimoine national',
                    'Pas d\'accès aux zones privées sans autorisation',
                ]),
                'contact_phone'     => '+216 75 860 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => true,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 70,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Côte de Djerba — Plage de Sidi Mahrez',
                'city'              => 'Houmt Souk',
                'region'            => 'Médenine',
                'commune'           => 'Houmt Souk',
                'description'       => 'Île méditerranéenne aux eaux turquoise — camping entre oliveraies millénaires et plages de sable blanc.',
                'full_description'  => 'Djerba, l\'île lotophage d\'Homère, offre un paysage unique en Tunisie : oliveraies, palmiers nains, plages de sable blanc et eaux limpides de la Méditerranée. La plage de Sidi Mahrez, sur la côte nord-est, reste l\'une des plus sauvages et préservées. La mosquée des Étrangers et la synagogue de la Ghriba témoignent du cosmopolitisme millénaire de l\'île. L\'été, l\'eau atteint 28°C ; l\'hiver, le climat doux permet un camping agréable sous les oliviers.',
                'terrain'           => 'Côtier & oliveraie',
                'difficulty'        => 'easy',
                'lat'               => 33.8076,
                'lng'               => 10.8449,
                'adresse'           => 'Plage Sidi Mahrez, Houmt Souk, Djerba',
                'distance'          => '500 km de Tunis',
                'altitude'          => '3m',
                'access_type'       => 'road',
                'accessibility'     => 'Chaussée goudronnée reliant Djerba au continent',
                'rating'            => 4.6,
                'reviews_count'     => 220,
                'best_season'       => json_encode(['Printemps', 'Été', 'Automne']),
                'activities'        => json_encode(['Baignade', 'Snorkeling', 'Kitesurf', 'Randonnée à vélo', 'Visite culturelle', 'Pêche', 'Photographie']),
                'facilities'        => json_encode(['Douches', 'WC', 'Parking', 'Restaurants', 'Location de vélos']),
                'rules'             => json_encode([
                    'Camping interdit sur les plages surveillées en été',
                    'Respecter les propriétés des oliveraies',
                    'Feux interdits en période sèche (mai–octobre)',
                ]),
                'contact_phone'     => '+216 75 650 000',
                'contact_email'     => null,
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => false,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 150,
                'map_zoom_level'    => 13,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
            [
                'nom'               => 'Jebel Bou Hedma',
                'city'              => 'Meknassy',
                'region'            => 'Sidi Bouzid',
                'commune'           => 'Meknassy',
                'description'       => 'Parc national de steppe aride — gazelles de Cuvier, outardes et forêts de genévriers relictuels.',
                'full_description'  => 'Le Jebel Bou Hedma (699 m) est l\'un des parcs nationaux les plus méconnus de Tunisie, classé réserve de biosphère UNESCO. Ses forêts de genévriers thurifères — vestiges d\'une végétation préhistorique — sont les dernières d\'Afrique du Nord. Le parc accueille un programme de réintroduction : gazelles de Cuvier, addax, oryx algazelle et outardes houbara. Bivouaquer ici permet d\'observer à l\'aube des espèces qu\'on ne trouve nulle part ailleurs en Tunisie.',
                'terrain'           => 'Steppe & montagne aride',
                'difficulty'        => 'medium',
                'lat'               => 34.5600,
                'lng'               => 9.5000,
                'adresse'           => 'Parc National Bou Hedma, Meknassy, Sidi Bouzid',
                'distance'          => '270 km de Tunis',
                'altitude'          => '500m',
                'access_type'       => 'road',
                'accessibility'     => '4x4 nécessaire pour les pistes intérieures',
                'rating'            => 4.5,
                'reviews_count'     => 38,
                'best_season'       => json_encode(['Printemps', 'Automne']),
                'activities'        => json_encode(['Safari faune sauvage', 'Randonnée', 'Observation des oiseaux', 'Photographie', 'Bivouac', 'Astronomie']),
                'facilities'        => json_encode(['Station de rangers', 'Parking à l\'entrée', 'Sentiers balisés']),
                'rules'             => json_encode([
                    'Permis obligatoire (DGFE Sidi Bouzid)',
                    'Respecter les zones d\'exclusion faunique',
                    'Véhicules limités à 30 km/h dans le parc',
                    'Feux strictement interdits',
                    'Ne pas approcher les animaux à moins de 50 m',
                ]),
                'contact_phone'     => '+216 76 630 000',
                'contact_email'     => 'bouhedma@dgfe.gov.tn',
                'contact_website'   => null,
                'is_public'         => true,
                'status'            => true,
                'is_protected_area' => true,
                'is_closed'         => false,
                'danger_level'      => 'low',
                'max_capacity'      => 20,
                'map_zoom_level'    => 12,
                'source'            => 'admin',
                'centre_id'         => null,
                'added_by'          => null,
            ],
        ];

        foreach ($zones as &$zone) {
            $zone['created_at'] = $now;
            $zone['updated_at'] = $now;
        }
        unset($zone);

        DB::table('camping_zones')->insertOrIgnore($zones);
        $this->command->info('✅ ' . count($zones) . ' zones de camping insérées.');

        // ─────────────────────────────────────────────────────────────────────
        // 2. CENTRES PRIVÉS  (status = 0)
        // ─────────────────────────────────────────────────────────────────────
        $centresPrives = [

            // ── Nord-Ouest ────────────────────────────────────────────────────
            [
                'nom'               => 'Camping La Forêt Verte',
                'type'              => 'centre',
                'description'       => 'Camping privé familial au cœur des forêts de chênes-lièges de la Kroumirie. Emplacements ombragés, chalets en bois et piscine naturelle alimentée par source.',
                'adresse'           => 'Route Forestière km 4, Ain Draham, Jendouba',
                'lat'               => 36.7650,
                'lng'               => 8.6890,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Les Pins du Corail',
                'type'              => 'centre',
                'description'       => 'Centre de camping haut de gamme à Tabarka, face à la mer. Bungalows, tentes glamping, club de plongée et restaurant de fruits de mer. À 300 m des célèbres Aiguilles.',
                'adresse'           => 'Route de la Plage, Tabarka, Jendouba',
                'lat'               => 36.9480,
                'lng'               => 8.7620,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Oued Zarga Nature',
                'type'              => 'centre',
                'description'       => 'Camping rustique au bord de l\'oued, entouré de chênes et d\'oliviers sauvages. Idéal pour les familles cherchant calme et nature à 1h de Tunis.',
                'adresse'           => 'Route de Testour, Oued Zarga, Béja',
                'lat'               => 36.8200,
                'lng'               => 9.5600,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],

            // ── Cap Bon & Grand Tunis ─────────────────────────────────────────
            [
                'nom'               => 'Camping Hammamet Vert',
                'type'              => 'centre',
                'description'       => 'Camping dans un jardin d\'orangers et de jasmin à 800 m de la plage de Hammamet. Accueil francophone, piscine, animations estivales et navette plage quotidienne.',
                'adresse'           => 'Route Touristique, Hammamet, Nabeul',
                'lat'               => 36.4000,
                'lng'               => 10.6150,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Korba Plage',
                'type'              => 'centre',
                'description'       => 'Terrain de camping en front de mer sur la côte est du Cap Bon. Emplacements pour tentes et camping-cars, sanitaires modernes, accès direct à la plage de sable fin.',
                'adresse'           => 'Plage de Korba, Korba, Nabeul',
                'lat'               => 36.5750,
                'lng'               => 10.8600,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Atlas Zaghouan',
                'type'              => 'centre',
                'description'       => 'Camping panoramique au pied du Jebel Zaghouan. Activités pleine nature : escalade, via ferrata, randonnée. Location de matériel et guides certifiés disponibles.',
                'adresse'           => 'Route du Parc National, Zaghouan',
                'lat'               => 36.3950,
                'lng'               => 10.1600,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Korbous Thermal',
                'type'              => 'centre',
                'description'       => 'Petit camping privé sur la falaise à Korbous. Accès privilégié aux vasques thermales, vue imprenable sur le golfe de Tunis. Capacité limitée à 20 tentes pour préserver le calme.',
                'adresse'           => 'Chemin des Sources, Korbous, Nabeul',
                'lat'               => 36.8100,
                'lng'               => 10.5700,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],

            // ── Centre & Côte Est ─────────────────────────────────────────────
            [
                'nom'               => 'Camping Les Oliviers de Sfax',
                'type'              => 'centre',
                'description'       => 'Camping au cœur de la plus grande oliveraie du monde (Sahel sfaxien). Séjours thématiques autour de l\'huile d\'olive, randonnées guidées et cuisine locale authentique.',
                'adresse'           => 'Route de Mahres km 12, Sfax',
                'lat'               => 34.6900,
                'lng'               => 10.7700,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Aqualand Nabeul',
                'type'              => 'centre',
                'description'       => 'Centre de camping balnéaire avec parc aquatique privatif, accès direct à la plage de Nabeul, animations pour enfants et adultes toute la saison estivale.',
                'adresse'           => 'Boulevard de la Plage, Nabeul',
                'lat'               => 36.4520,
                'lng'               => 10.7320,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'pending',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Eco-Berber Matmata',
                'type'              => 'centre',
                'description'       => 'Éco-camping en habitat troglodytique restauré. Nuits dans des chambre creusées dans la roche, cuisine berbère traditionnelle, balade en dromadaire et visite des ateliers artisanaux.',
                'adresse'           => 'Village Troglodytique, Matmata, Gabès',
                'lat'               => 33.5350,
                'lng'               => 9.9720,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],

            // ── Sud Saharien ──────────────────────────────────────────────────
            [
                'nom'               => 'Camping Étoile du Sahara',
                'type'              => 'centre',
                'description'       => 'Camp de luxe à 4 km de Tozeur. Tentes berbères climatisées, dîners gastronomiques sous les étoiles, excursions en 4x4 vers le Chott el-Djerid et les tournages Star Wars.',
                'adresse'           => 'Route de Nefta km 4, Tozeur',
                'lat'               => 33.9100,
                'lng'               => 8.1100,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Dunes Dorées — Douz',
                'type'              => 'centre',
                'description'       => 'Camp saharien authentique à la lisière des dunes de Douz. Tentes nomades, musique gnaoua au coucher du soleil, excursions chameau au lever du jour. Gérant : famille Baccar depuis 1989.',
                'adresse'           => 'Zone des Dunes, Douz, Kébili',
                'lat'               => 33.4400,
                'lng'               => 9.0400,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Desert Rose Camp — Ksar Ghilane',
                'type'              => 'centre',
                'description'       => 'Camp privé à l\'oasis de Ksar Ghilane, unique en Tunisie. 25 tentes nomades autour de la source thermale (30°C), excursions quad, bivouacs avancés dans l\'erg et service de convois 4x4.',
                'adresse'           => 'Oasis Ksar Ghilane, Tataouine',
                'lat'               => 32.9764,
                'lng'               => 9.6369,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
            [
                'nom'               => 'Camping Ksour Adventure',
                'type'              => 'centre',
                'description'       => 'Base camp privé pour l\'exploration des ksour de Tataouine. Randonnées guidées vers Ksar Ouled Soltane et Ksar Hadada, cuisine troglodytique et soirées contes berbères.',
                'adresse'           => 'Route des Ksour, Ghomrassen, Tataouine',
                'lat'               => 33.0700,
                'lng'               => 10.1900,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],

            // ── Djerba ────────────────────────────────────────────────────────
            [
                'nom'               => 'Camping Djerba Soleil',
                'type'              => 'centre',
                'description'       => 'Camping 3 étoiles sur l\'île de Djerba, dans un jardin de palmiers à 200 m de la mer. Piscine, restaurant, location de vélos et de kayaks. Accueil en français, arabe et allemand.',
                'adresse'           => 'Zone Touristique Midoun, Djerba, Médenine',
                'lat'               => 33.7950,
                'lng'               => 11.0150,
                'image'             => null,
                'status'            => 0,
                'validation_status' => 'approved',
                'user_id'           => null,
                'profile_centre_id' => null,
            ],
        ];

        foreach ($centresPrives as &$c) {
            $c['created_at'] = $now;
            $c['updated_at'] = $now;
        }
        unset($c);

        DB::table('camping_centres')->insertOrIgnore($centresPrives);
        $this->command->info('✅ ' . count($centresPrives) . ' centres privés insérés.');

        // ─────────────────────────────────────────────────────────────────────
        // 3. CENTRES PUBLICS / NON PRIVÉS  (status = 1)  — complément CRJT/MJ
        // ─────────────────────────────────────────────────────────────────────
        $centresPublics = [

            // Ariana / Grand Tunis
            ['nom' => 'CCV Borj Turki',          'type' => 'CCV', 'description' => 'Camping balnéaire nord du golfe de Tunis',         'adresse' => 'Borj Turki, Ariana',              'lat' => 37.0800, 'lng' => 10.2100],
            ['nom' => 'MJ La Marsa',              'type' => 'MJ',  'description' => 'Maison de jeunes balnéaire',                       'adresse' => 'La Marsa, Tunis',                 'lat' => 36.8840, 'lng' => 10.3232],
            ['nom' => 'CJ El Menzah',             'type' => 'CJ',  'description' => 'Complexe de jeunes urbain',                        'adresse' => 'El Menzah, Tunis',                'lat' => 36.8419, 'lng' => 10.1916],

            // Bizerte (compléments)
            ['nom' => 'CCV Cap Negro',            'type' => 'CCV', 'description' => 'Camping forestier et balnéaire',                    'adresse' => 'Cap Negro, Bizerte',              'lat' => 37.2500, 'lng' => 9.2100],
            ['nom' => 'MJ Ras Jebel',             'type' => 'MJ',  'description' => 'Maison de jeunes côtière',                         'adresse' => 'Ras Jebel, Bizerte',              'lat' => 37.2160, 'lng' => 10.1290],

            // Nabeul / Cap Bon
            ['nom' => 'CCV Kelibia',              'type' => 'CCV', 'description' => 'Camping balnéaire Cap Bon nord-est',               'adresse' => 'Kelibia, Nabeul',                 'lat' => 36.8467, 'lng' => 11.1140],
            ['nom' => 'MJ Menzel Temime',         'type' => 'MJ',  'description' => 'Maison de jeunes côtière',                         'adresse' => 'Menzel Temime, Nabeul',           'lat' => 36.7830, 'lng' => 10.9800],
            ['nom' => 'CCV Hammamet Sud',         'type' => 'CCV', 'description' => 'Camping balnéaire touristique',                    'adresse' => 'Hammamet, Nabeul',                'lat' => 36.3500, 'lng' => 10.5900],

            // Monastir / Sousse
            ['nom' => 'CCV Akouda',               'type' => 'CCV', 'description' => 'Camping balnéaire Sahel',                          'adresse' => 'Akouda, Sousse',                  'lat' => 35.9000, 'lng' => 10.5600],
            ['nom' => 'MJ Sousse Jawhara',        'type' => 'MJ',  'description' => 'Maison de jeunes urbaine côtière',                  'adresse' => 'Sousse',                          'lat' => 35.8287, 'lng' => 10.6371],
            ['nom' => 'CCV Monastir Corniche',    'type' => 'CCV', 'description' => 'Camping balnéaire Monastir',                       'adresse' => 'Monastir',                        'lat' => 35.7783, 'lng' => 10.8262],

            // Mahdia
            ['nom' => 'CCV Mahdia El Abassia',   'type' => 'CCV', 'description' => 'Camping balnéaire Mahdia',                         'adresse' => 'Mahdia',                          'lat' => 35.5060, 'lng' => 11.0620],
            ['nom' => 'MJ El Jem',                'type' => 'MJ',  'description' => 'Maison de jeunes archéologique',                   'adresse' => 'El Jem, Mahdia',                  'lat' => 35.2967, 'lng' => 10.7081],

            // Sfax
            ['nom' => 'CCV Sidi Mansour',        'type' => 'CCV', 'description' => 'Camping balnéaire Sfax',                           'adresse' => 'Sidi Mansour, Sfax',              'lat' => 34.7750, 'lng' => 10.7900],
            ['nom' => 'CJ Sfax Riadh',           'type' => 'CJ',  'description' => 'Complexe de jeunes urbain',                        'adresse' => 'Sfax',                            'lat' => 34.7400, 'lng' => 10.7600],

            // Médenine / Tataouine
            ['nom' => 'CCV Zarzis',              'type' => 'CCV', 'description' => 'Camping balnéaire saharien',                       'adresse' => 'Zarzis, Médenine',                'lat' => 33.5067, 'lng' => 11.1117],
            ['nom' => 'MJ Ben Gardane',          'type' => 'MJ',  'description' => 'Maison de jeunes frontalière',                     'adresse' => 'Ben Gardane, Médenine',           'lat' => 33.1375, 'lng' => 11.2214],
            ['nom' => 'CJ Tataouine',            'type' => 'CJ',  'description' => 'Complexe saharien ksour',                          'adresse' => 'Tataouine',                       'lat' => 32.9302, 'lng' => 10.4513],

            // Gabès
            ['nom' => 'CCV Gabès Plage',         'type' => 'CCV', 'description' => 'Camping balnéaire oasis maritime',                 'adresse' => 'Gabès Plage, Gabès',              'lat' => 33.8925, 'lng' => 10.1200],
            ['nom' => 'MJ Mareth',               'type' => 'MJ',  'description' => 'Maison de jeunes historique (front de guerre WWII)','adresse' => 'Mareth, Gabès',                  'lat' => 33.6400, 'lng' => 10.0500],

            // Tozeur / Kébili
            ['nom' => 'CCV Tozeur Oasis',        'type' => 'CCV', 'description' => 'Camping saharien dans la palmeraie',               'adresse' => 'Tozeur',                          'lat' => 33.9197, 'lng' => 8.1335],
            ['nom' => 'CCV Nefta Desert',        'type' => 'CCV', 'description' => 'Camping saharien à l\'orée de la Corbeille',       'adresse' => 'Nefta, Tozeur',                   'lat' => 33.8703, 'lng' => 7.8800],

            // Sidi Bouzid / Kairouan (compléments)
            ['nom' => 'MJ Sidi Bouzid',          'type' => 'MJ',  'description' => 'Maison de jeunes rurale centrale',                 'adresse' => 'Sidi Bouzid',                     'lat' => 35.0381, 'lng' => 9.4858],
            ['nom' => 'CCV Bou Hafna',           'type' => 'CCV', 'description' => 'Camping lacustre barrage Sidi Saad',               'adresse' => 'Bou Hafna, Kairouan',             'lat' => 35.4200, 'lng' => 9.7800],

            // Le Kef / Siliana (compléments)
            ['nom' => 'CCV Jebba',               'type' => 'CCV', 'description' => 'Camping forestier nord-ouest',                     'adresse' => 'Jebba, Le Kef',                   'lat' => 36.3600, 'lng' => 8.8000],
            ['nom' => 'MJ Siliana',              'type' => 'MJ',  'description' => 'Maison de jeunes forestière',                      'adresse' => 'Siliana',                         'lat' => 36.0842, 'lng' => 9.3702],
        ];

        foreach ($centresPublics as &$cp) {
            $cp['image']             = null;
            $cp['status']            = 1;
            $cp['validation_status'] = 'approved';
            $cp['user_id']           = null;
            $cp['profile_centre_id'] = null;
            $cp['created_at']        = $now;
            $cp['updated_at']        = $now;
        }
        unset($cp);

        DB::table('camping_centres')->insertOrIgnore($centresPublics);
        $this->command->info('✅ ' . count($centresPublics) . ' centres publics insérés.');

        $this->command->info('🏕️  TunisiaCampingSeeder terminé avec succès !');
    }
}
