<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        $users = [
            // Admin user (role_id = 6)
            [
                'id' => 1,
                'first_name' => 'Admin',
                'last_name' => 'User',
                'email' => 'admin@tunisiacamp.tn',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123456',
                'ville' => 'Tunis',
                'date_naissance' => '1990-01-01',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 6,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Center Manager (role_id = 3) - njkhouja@gmail.com
            [
                'id' => 2,
                'first_name' => 'Center',
                'last_name' => 'Manager',
                'email' => 'njkhouja@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123457',
                'ville' => 'Tunis',
                'date_naissance' => '1985-03-15',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 3,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Camper (role_id = 1) - deadxshot660@gmail.com
            [
                'id' => 3,
                'first_name' => 'DeadXShot',
                'last_name' => 'Camper',
                'email' => 'deadxshot660@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123458',
                'ville' => 'Sousse',
                'date_naissance' => '1995-05-20',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 1,
                'is_active' => 1,
                'first_login' => 1,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Group user (role_id = 2) - nejikh57@gmail.com
            [
                'id' => 4,
                'first_name' => 'Nejikh',
                'last_name' => 'Group',
                'email' => 'nejikh57@gmail.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123459',
                'ville' => 'Bizerte',
                'date_naissance' => '1988-11-10',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 2,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Additional Group Users (role_id = 2) for variety
            [
                'id' => 5,
                'first_name' => 'Forest',
                'last_name' => 'Rangers',
                'email' => 'forest.rangers@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123460',
                'ville' => 'Jendouba',
                'date_naissance' => '1992-04-25',
                'sexe' => 'female',
                'langue' => 'fr',
                'role_id' => 2,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'first_name' => 'Coastal',
                'last_name' => 'Adventures',
                'email' => 'coastal@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123461',
                'ville' => 'Mahdia',
                'date_naissance' => '1987-09-12',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 2,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Suppliers (role_id = 4)
            [
                'id' => 7,
                'first_name' => 'Camp',
                'last_name' => 'Equipment',
                'email' => 'equipment@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123462',
                'ville' => 'Sfax',
                'date_naissance' => '1980-12-05',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 4,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Guides (role_id = 5)
            [
                'id' => 8,
                'first_name' => 'Ahmed',
                'last_name' => 'Guide',
                'email' => 'ahmed.guide@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123463',
                'ville' => 'Tunis',
                'date_naissance' => '1990-06-18',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 5,
                'is_active' => 1,
                'first_login' => 0,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Additional Campers (role_id = 1)
            [
                'id' => 9,
                'first_name' => 'Sarah',
                'last_name' => 'Camper',
                'email' => 'sarah@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123464',
                'ville' => 'Bizerte',
                'date_naissance' => '1997-02-14',
                'sexe' => 'female',
                'langue' => 'fr',
                'role_id' => 1,
                'is_active' => 1,
                'first_login' => 1,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'first_name' => 'Mike',
                'last_name' => 'Smith',
                'email' => 'mike@example.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password'),
                'phone_number' => '+21650123465',
                'ville' => 'Nabeul',
                'date_naissance' => '1993-11-30',
                'sexe' => 'male',
                'langue' => 'fr',
                'role_id' => 1,
                'is_active' => 1,
                'first_login' => 1,
                'nombre_signalement' => 0,
                'last_login_at' => null,
                'avatar' => null,
                'preferences' => null,
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}