<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Balance;
use App\Models\Reservations_centre;
use App\Models\Reservations_events;
use App\Models\Reservations_materielles;
use App\Models\WalletRechargeRequest;
use App\Models\User;
use App\Models\WalletTransaction;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class AdminUserTrackController extends Controller
{
    /**
     * Search users by name or email (min 2 chars).
     */
    public function search(Request $request)
    {
        $q = trim($request->get('q', ''));
        if (mb_strlen($q) < 2) {
            return response()->json(['users' => []]);
        }

        $users = User::where(function ($query) use ($q) {
            $query->where('first_name', 'like', "%{$q}%")
                  ->orWhere('last_name',  'like', "%{$q}%")
                  ->orWhere('email',      'like', "%{$q}%");
        })
        ->select('id', 'first_name', 'last_name', 'email', 'role_id', 'created_at')
        ->orderBy('first_name')
        ->limit(12)
        ->get()
        ->map(function ($u) {
            $balance = Balance::where('user_id', $u->id)->first();
            return [
                'id'          => $u->id,
                'first_name'  => $u->first_name,
                'last_name'   => $u->last_name,
                'email'       => $u->email,
                'role_id'     => $u->role_id,
                'created_at'  => $u->created_at,
                'disponible'  => (float) ($balance->solde_disponible ?? 0),
                'en_attente'  => (float) ($balance->solde_en_attente ?? 0),
            ];
        });

        return response()->json(['users' => $users]);
    }

    /**
     * Full monetary audit for one user:
     *  - current balance
     *  - all wallet transactions (debits + credits)
     *  - platform revenue generated by / from this user
     */
    public function audit(int $userId)
    {
        $user = User::findOrFail($userId);
        $balance = Balance::where('user_id', $userId)->first();

        // ── Wallet transactions ────────────────────────────────────────────────
        $transactions = WalletTransaction::where('user_id', $userId)
            ->orderBy('created_at', 'desc')
            ->get()
            ->map(fn($t) => [
                'id'             => $t->id,
                'type'           => $t->type,           // debit | credit
                'category'       => $t->category,
                'amount_gross'   => (float) $t->amount_gross,
                'commission_rate'   => (float) ($t->commission_rate ?? 0),
                'commission_amount' => (float) ($t->commission_amount ?? 0),
                'net_amount'     => (float) ($t->net_amount ?? $t->amount_gross),
                'reference_type' => $t->reference_type,
                'reference_id'   => $t->reference_id,
                'description'    => $t->description,
                'created_at'     => $t->created_at,
            ]);

        // ── Platform revenue AS CAMPER (fees the platform charged on their bookings) ─
        $centreFeesCamper = (float) Reservations_centre::where('user_id', $userId)
            ->whereNotNull('platform_fee_amount')
            ->sum('platform_fee_amount');

        $eventFeesCamper = (float) Reservations_events::where('user_id', $userId)
            ->whereNotNull('platform_fee_amount')
            ->sum('platform_fee_amount');

        $materielFeesCamper = (float) Reservations_materielles::where('user_id', $userId)
            ->whereNotNull('platform_fee_amount')
            ->sum('platform_fee_amount');

        $totalFeesFromCamper = round($centreFeesCamper + $eventFeesCamper + $materielFeesCamper, 2);

        // Reservation counts as camper
        $reservationCountsCamper = [
            'centre'    => Reservations_centre::where('user_id', $userId)->count(),
            'events'    => Reservations_events::where('user_id', $userId)->count(),
            'materiel'  => Reservations_materielles::where('user_id', $userId)->count(),
        ];

        // ── Platform revenue AS PROVIDER (commission taken from payouts to this user) ─
        $commissionsAsProvider = (float) WalletTransaction::where('user_id', $userId)
            ->where('type', 'credit')
            ->where('commission_amount', '>', 0)
            ->sum('commission_amount');

        // Reservations received as supplier (fournisseur) or centre
        $reservationsAsSupplier = Reservations_materielles::where('fournisseur_id', $userId)->count();
        $reservationsAsCentre   = Reservations_centre::where('centre_id', $userId)->count();

        // ── Total debited / credited ever ─────────────────────────────────────
        $totalDebited  = (float) WalletTransaction::where('user_id', $userId)->where('type', 'debit')->sum('amount_gross');
        $totalCredited = (float) WalletTransaction::where('user_id', $userId)->where('type', 'credit')->sum('amount_gross');

        // ── Total refunds received ────────────────────────────────────────────
        $totalRefunds = (float) WalletTransaction::where('user_id', $userId)
            ->where('type', 'credit')
            ->where('category', 'refund_in')
            ->sum('amount_gross');

        // ── Manual payment reservations ───────────────────────────────────────
        $manualFields = ['id', 'payment_reference', 'payment_option', 'payment_method',
                         'amount_now', 'amount_later', 'balance_due_at', 'status',
                         'payment_submitted_at', 'payment_confirmed_at', 'created_at'];

        $manualEvents = Reservations_events::where('user_id', $userId)
            ->where('payment_method', 'manual')
            ->latest()->get($manualFields)
            ->map(fn($r) => array_merge($r->toArray(), ['reservation_type' => 'event']));

        $manualCentres = Reservations_centre::where('user_id', $userId)
            ->where('payment_method', 'manual')
            ->latest()->get($manualFields)
            ->map(fn($r) => array_merge($r->toArray(), ['reservation_type' => 'centre']));

        $manualMaterielles = Reservations_materielles::where('user_id', $userId)
            ->where('payment_method', 'manual')
            ->latest()->get($manualFields)
            ->map(fn($r) => array_merge($r->toArray(), ['reservation_type' => 'materiel']));

        $allManualReservations = $manualEvents->concat($manualCentres)->concat($manualMaterielles)
            ->sortByDesc('created_at')->values();

        $walletRecharges = WalletRechargeRequest::where('user_id', $userId)
            ->latest()->get(['id', 'amount', 'payment_reference', 'status', 'submitted_at', 'confirmed_at', 'created_at'])
            ->map(fn($r) => $r->toArray());

        return response()->json([
            'user' => [
                'id'         => $user->id,
                'first_name' => $user->first_name,
                'last_name'  => $user->last_name,
                'email'      => $user->email,
                'role_id'    => $user->role_id,
                'created_at' => $user->created_at,
            ],
            'balance' => [
                'disponible'      => (float) ($balance->solde_disponible   ?? 0),
                'en_attente'      => (float) ($balance->solde_en_attente   ?? 0),
                'total_encaisse'  => (float) ($balance->total_encaisse     ?? 0),
                'total_retire'    => (float) ($balance->total_retire       ?? 0),
                'total_rembourse' => (float) ($balance->total_rembourse    ?? 0),
            ],
            'transactions' => $transactions,
            'summary' => [
                'total_debited'  => round($totalDebited,  2),
                'total_credited' => round($totalCredited, 2),
                'total_refunds'  => round($totalRefunds,  2),
                'net_flow'       => round($totalCredited - $totalDebited, 2),
            ],
            'platform_revenue' => [
                'fees_as_camper' => [
                    'total'    => $totalFeesFromCamper,
                    'centre'   => round($centreFeesCamper,   2),
                    'events'   => round($eventFeesCamper,    2),
                    'materiel' => round($materielFeesCamper, 2),
                ],
                'commissions_as_provider' => round($commissionsAsProvider, 2),
                'total' => round($totalFeesFromCamper + $commissionsAsProvider, 2),
            ],
            'activity' => [
                'reservations_as_camper'   => $reservationCountsCamper,
                'reservations_as_supplier' => $reservationsAsSupplier,
                'reservations_as_centre'   => $reservationsAsCentre,
            ],
            'manual_payments' => [
                'reservations'    => $allManualReservations,
                'wallet_recharges'=> $walletRecharges,
            ],
        ]);
    }

    /**
     * List all admin-initiated balance adjustments (global, across all users).
     * Paginated, filterable by type (admin_credit / admin_debit) and user.
     */
    public function balanceHistory(Request $request)
    {
        $perPage = min((int) $request->get('per_page', 25), 100);
        $type    = $request->get('type');  // 'admin_credit' | 'admin_debit' | null (all)
        $userId  = $request->get('user_id');
        $search  = trim($request->get('search', ''));

        $query = WalletTransaction::with(['user:id,first_name,last_name,email', 'relatedUser:id,first_name,last_name'])
            ->whereIn('category', ['admin_credit', 'admin_debit'])
            ->when($type,   fn($q) => $q->where('category', $type))
            ->when($userId, fn($q) => $q->where('user_id', $userId))
            ->when($search, fn($q) => $q->whereHas('user', fn($uq) =>
                $uq->where('first_name', 'like', "%{$search}%")
                   ->orWhere('last_name',  'like', "%{$search}%")
                   ->orWhere('email',      'like', "%{$search}%")
            ))
            ->orderBy('created_at', 'desc');

        $paginated = $query->paginate($perPage);

        $items = $paginated->map(fn($t) => [
            'id'           => $t->id,
            'category'     => $t->category,
            'type'         => $t->type,
            'amount'       => (float) $t->amount_gross,
            'description'  => $t->description,
            'created_at'   => $t->created_at,
            'user'         => $t->user ? [
                'id'         => $t->user->id,
                'first_name' => $t->user->first_name,
                'last_name'  => $t->user->last_name,
                'email'      => $t->user->email,
            ] : null,
            'admin'        => $t->relatedUser ? [
                'id'         => $t->relatedUser->id,
                'first_name' => $t->relatedUser->first_name,
                'last_name'  => $t->relatedUser->last_name,
            ] : null,
        ]);

        // Summary totals for header
        $totals = WalletTransaction::whereIn('category', ['admin_credit', 'admin_debit'])
            ->selectRaw("category, SUM(amount_gross) as total, COUNT(*) as count")
            ->groupBy('category')
            ->get()
            ->keyBy('category');

        return response()->json([
            'data'       => $items,
            'meta'       => [
                'current_page' => $paginated->currentPage(),
                'last_page'    => $paginated->lastPage(),
                'per_page'     => $paginated->perPage(),
                'total'        => $paginated->total(),
            ],
            'totals' => [
                'admin_credit' => [
                    'total' => (float) ($totals['admin_credit']->total ?? 0),
                    'count' => (int)   ($totals['admin_credit']->count ?? 0),
                ],
                'admin_debit' => [
                    'total' => (float) ($totals['admin_debit']->total ?? 0),
                    'count' => (int)   ($totals['admin_debit']->count ?? 0),
                ],
            ],
        ]);
    }

    /**
     * Manually credit or debit a user's available balance.
     */
    public function balanceAdjust(Request $request)
    {
        $data = $request->validate([
            'user_id'     => 'required|integer|exists:users,id',
            'type'        => 'required|in:credit,debit',
            'amount'      => 'required|numeric|min:0.01|max:10000',
            'description' => 'required|string|min:3|max:255',
        ]);

        $user    = User::findOrFail($data['user_id']);
        $amount  = round((float) $data['amount'], 2);
        $balance = Balance::forUser($user->id);
        $adminId = Auth::id();

        if ($data['type'] === 'debit' && $balance->solde_disponible < $amount) {
            return response()->json([
                'success' => false,
                'message' => "Insufficient balance. User only has {$balance->solde_disponible} TND available.",
            ], 422);
        }

        DB::beginTransaction();
        try {
            if ($data['type'] === 'credit') {
                $balance->crediter($amount);
                WalletTransaction::logCredit(
                    $user->id, 'admin_credit',
                    $amount, 0, 0, $amount,
                    'admin_adjustment', null,
                    $data['description'],
                    $adminId
                );
            } else {
                $balance->debiter($amount);
                WalletTransaction::logDebit(
                    $user->id, 'admin_debit',
                    $amount,
                    'admin_adjustment', null,
                    $data['description'],
                    $adminId
                );
            }
            DB::commit();
        } catch (\Throwable $e) {
            DB::rollBack();
            \Log::error('Admin balance adjustment failed', ['error' => $e->getMessage(), 'data' => $data]);
            return response()->json(['success' => false, 'message' => 'Adjustment failed. Please try again.'], 500);
        }

        $fresh = Balance::where('user_id', $user->id)->first();

        return response()->json([
            'success' => true,
            'message' => ucfirst($data['type']) . " of {$amount} TND applied to {$user->first_name} {$user->last_name}.",
            'new_balance' => [
                'disponible' => (float) $fresh->solde_disponible,
                'en_attente' => (float) $fresh->solde_en_attente,
            ],
        ]);
    }
}
